* C++ in Action
** Language
*** Objects and Scopes
**** Global Scope
- Class definition
- Object definition
- Constructor
- Destructor
- Output stream
- Include
- Main


#+begin_src c++
  // Include statement
  #include <iostream> // Tells the compiler to find the file iostream and include it.
  //           |
  //           ----> part of the standard C++ library, not part of the language.
  // Class definition
    class World // A class is a type defined by a programmer.
    { // The class definition is inside the curly braces.
	public: // Means that we have nothing to hide yet (data hiding).
	   World () // A Constructor is a piece of code that is to be executed everytime an object of this particular class is created.
	   {           //    |
		       //    ----> Always have the same name as the class itself.
		       //    ----> May take any arguments - that's why it has a set of parentheses.
	       std::cout << "Hello!" << std::endl; // ----> the object std::cout is sent the string "Hello!"
	       // |                        |
	       // |                        ----> end line (creates a new line).
	       // ----> represents the standard output, presumably the screen of the computer, and it prints whatever is sent to it.
	   }
	   ~World () // A destructor always has the same name as the class but is preceeded with tilde (~).
	   {         // A piece of code that is executed every time an object of this class is destroyed.
		     // Never takes any arguments.
	       std::cout << "Good bye!" << std::endl; // ----> prints "Good bye!"
	   }
    }; // A class is delimited by a semi-colon.

  // Object definition --> This is the central line of the program.
    World TheWorld; // --> "TheWorld" is an instance of the class "World".
	       // |
	       // ----> A statement is delimited by a semi-colon (;).
  // Main routine
    void main ()
    {
	return 0;
    }
#+end_src


- _Global scope_ is everything outside of curly braces.
- Top-down approach is the correct way of analyzing a program and creating it.


Program flow:
1. All global objects are constructed. The constructer executes it's instructions.
2. The main routine is executed.
3. All global objects are destroyed. The destructor is executed.


- Building means compiling and linking.


Summary: We have introduced a class and an object. Think of a class as a blueprint for an object.
It describes the object's behavior - in our case, what happens when the object is constructed
and destroyed. Once you have a blue print, you can create objects that are based on it.


Note: One could think of main as the constructor of the global Main object. This is how
truly object oriented languages work.


**** Local Scope
- Scope of main
- Passing arguments to constructors
- Interger type
- Private data members
- Initialization
- Embedded local scopes
- The for loop


- Global scope is activated (ready to use, all objects constructed) before main is executed,
  and deactivated (all objects destroyed) after main is exited.
- Local scopes are delimited by braces (not always)
  - Activated when the flow of the program enters it, and
    deactivated when it leaves it.
  - Objects in local scope are constructed whenever their definition is encountered,
    and destroyed when the scope is exited.
    - Such objects are called _automatic_ (because they are automatically created and destroyed),
      or _stack objects_ (because they occupy memory that is allocated on the program's stack).


#+begin_src c++
  #include <iostream>

  class World
  {
    public:
    World (int i)
    {
      std::cout << "Hello from " << i << "." << std::endl;
    }

    ~World ()
    {
      std::cout << "Good bye." << std::cout;
    }
  };

  World TheWorld (1);

  int main ()
    {
      World myWorld (2);
      std::cout << "Hello from main!" << std::endl;
      return 0;
    }
#+end_src


- std::cout accepts strings of characters and prints them as string
  and it accepts integers and prints them as decimal numbers.
- You can chain arguments to std::cout one after another.
- An _object_ is something that has identity.
- If possible, stick to /countable/ nouns in naming classes.


#+begin_src c++
  #include <iostream>

  class World
  {
    public:
    World (int id)
      : _identifier (id)
    {
      std::cout << "Hello from " << _identifier << "." << std::endl;
    }

    ~World ()
    {
      std::cout << "Good bye from " << _identifier << "." << std::endl;
    }

    private:
      const int _identifier;
  };

  World TheWorld (1);

  int main ()
    {
      World myWorld (2);
      for (int i = 3; i < 6; ++i)
	{
	  World aWorld (i);
	}
      World oneMoreWorld (6);
      
      return 0;
    }
#+end_src

- The braces delimiting the scope may be omitted if the body of the loop
  consists of a single statement.
  #+begin_src c++
    for (int i = 3; i < 6; ++i)
      World aWorld (i);
  #+end_src
- The scope of a variable defined in the head of a loop (or the ~if~ statement)
  is that of the loop itself.
- Variables defined in the body of the loop are re-initialized on every iteration.
- The ones defined in the head are initialized once, at the loop entry. However,
  once you exit the loop, neither are accessible.
- The compiler will make sure that nobody, except the class itself,
  has access to *private members*.
- The keyword ~const~ means that nobody can change the value of ~_identifier~ during the lifetime of the object.
- The *preamble* to the constructor is the little window when we can (and have to)
  initialize a ~const~ data member.


Summary: Objects may have their own memory, or state. The state data members are preferably kept private.
They are best initialized in the preamble to the constructor, so that the object is in a consistent state
immediately after its birth. The "for loop" creates its own scope. This scope is entered an exited during
every iteration. In fact, a matched pair of braces can be put anywhere within another scope, just to form
a sub-scope.

**** Embedded Objects
- Embeddings
- Initialization of embeddings
- Order of construction/destruction


#+begin_src C++
  #include <iostream>
  class Matter
  {
    public:
    Matter (int id)
    : _identifier (id)
    {
      std::cout << " Matter for " << _identifier << " created." << std::endl;
    }

    ~Matter ()
    {
      std::cout << " Matter in " << _identifier << " annihilated." << std::endl;
    }

    private:
    const int _identifier;
  };

  class World
  {
    public:
    World (int id)
    : _identifier (id), _matter (_identifier) // initializing embeddings
    {
      std::cout << "Hello from world " << _identifier << "." << std::endl;
    }

    ~World ()
    {
      std::cout << "Good bye from world " << _identifier << "." << std::endl;
    }

    private:
    const int _identifier;
    const Matter _matter; // Embedded object of type Matter
  };

  World TheUniverse (1);

  int main ()
  {
    World myWorld (2);
    return 0;
  }
#+end_src

- *Data members* are initialized in the order in which they appear in the class
  definition.
- Embedded object = has-a


Summary: Objects of programmer defined types maybe embedded as data members in
other classes. The constructors for the embeddings are called before the body
of the object's constructor is executed (conceptually you may visualize them
as being called in the preamble). If these constructors need arguments, they
must be passed in the preamble. The order of construction is determined by the
order of embeddings. The embeddings are destroyed in the reverse order of
construction.



**** Inheritance
- Public Inheritance
- Initialization of the base class
- Order of construction/destruction
- Type double


#+begin_src C++
      #include <iostream>

      class CelestialBody
      {
      public:
	CelestialBody (double mass)
	  : _mass (mass)
	{
	  std::cout << "Creating celestial body of mass " << _mass << "." << std::endl;
	}

	~CelestialBody ()
	{
	  std::cout << "Destroying celestial body of mass " << _mass << "." << std::endl;
	}

      private:
	const double _mass;
    };

    class Star: public CelestialBody // Star is a CelestialBody
    {
    public:
      Star (double mass, double brightness)
	: CelestialBody (mass), _brightness (brightness)
      {
	std::cout << "Creating a star of brightness " <<
	  _brightness << "." << std::endl;
      }

      ~Star ()
      {
	std::cout << "Destroying a star of brightness " <<
	  _brightness << "." << std::endl;
      }

    private:
      const double _brightness;
  };

  int main ()
    {
      std::cout << "    Entering main." << std::endl;
      Start aStar (1234.5, 0.1);
      std::cout << "    Exiting main." << std::endl;

      return 0;
    }
#+end_src


- First the base class id fully constructed, then the derived class.
- The order in the preamble is meaninglless, and if there are no explicit initializations
  the whole thing may be omitted.


**** Member functions and interfaces
- Input stream
- Member functions (methods)
- Return values
- Interfaces
- Functions returning void


- *Methods* - bahavior exposed via member function


#+begin_src C++
  #include <iostream>

  class InputNum
  {
    public:
      InputNum ()
      {
	std::cout << "Enter number : ";
	std::cin >> _num;
      }

      int GetValue () const
      {
	return _num;
      }

    private:
      int _num;
  };

  int main ()
  {
    InputNum num;

    std::cout << "The value is " << num.GetValue () << std::endl;
    return 0;
  }
#+end_src


Summary: The set of public member functions defines the interface
to the object of the given class. What is even more important, a well
designed and well implemented object is able to fulfill a well defined
contract. Programming in C++ is about writing contracts and fulfilling
them. An interface can, and should, be designed in such a way that the
client's part of the contract is simple and well defined. The object
may even be able to protect itself from sloppy clients wo break their
part of the contract.


